---
title: "Final Project"
author: "Yikun Zhou"
date: "November 27, 2014"
output: html_document
---

# Exploring data
```{r}
library(gam)
library(MASS)
library(car)
data <- read.table("costs.txt",header=T)
data <- data[1:8]

panel.hist <- function(x, ...)
{
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(usr[1:2], 0, 1.5) )
    h <- hist(x, plot = FALSE)
    breaks <- h$breaks; nB <- length(breaks)
    y <- h$counts; y <- y/max(y)
    rect(breaks[-nB], 0, breaks[-1], y, col = "cyan", ...)
}

panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...)
{
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(0, 1, 0, 1))
    r <- abs(cor(x, y))
    txt <- format(c(r, 0.123456789), digits = digits)[1]
    txt <- paste0(prefix, txt)
    if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
    text(0.5, 0.5, txt, cex = cex.cor * r)
}

pairs(data,lower.panel = panel.smooth, upper.panel = panel.cor, diag.panel = panel.hist)
```
It seems that there exist non-linearity in variable RXPM. Colinearity in Copay, RI and Age. Also, MM seem to be a much larger scale of data than others, so we can take logrithm to it.

detect colinearity
```{r}
lm.1 <- lm(COST~.,data)
vif(lm.1)
```
no colinearity exists.

data transformation
```{r}
logMM <- log(data$MM)
data1 <- data
data1$MM <- logMM
```


```{r}
lm.2 <- lm(COST~.,data=data1)
anova(lm.1,lm.2)
```

try gam

```{r}
gam.1 <- gam(COST ~ RXPM + s(GS,4) + RI + COPAY + AGE + F + MM,data=data1)
summary(gam.1)
anova(lm.1,lm.2,gam.1)
```

